version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: sh -c "yarn && npm run start:dev"
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/client:/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: sh -c "npm run start"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - ./frontend/client/.env.development